# Generated by Django 6.0 on 2026-02-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startlet', '0003_announcement_invoice_trainerearning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='role',
            field=models.CharField(choices=[('TRAINER', 'Trainer'), ('CLIENT', 'Client'), ('MANAGER', 'Manager')], default='CLIENT', max_length=10),
        ),
    ]
