# Generated by Django 5.2.16 on 2026-07-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startlet', '0005_alter_announcement_id_alter_branch_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotGenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ran_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('branches_processed', models.IntegerField(default=0)),
                ('slots_created', models.IntegerField(default=0)),
                ('details', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-ran_at'],
            },
        ),
    ]
